@workerUrl=http://localhost:5556
@managerUrl=http://localhost:5555


# Get Worker Tasks
GET {{workerUrl}}/tasks

###

# Start a Worker Task
POST {{workerUrl}}/tasks

{
    "ID": "266592cd-960d-4091-981c-8c25c44b1018",
    "State": 2,
    "Task": {
        "State": 1,
        "ID": "266592cd-960d-4091-981c-8c25c44b1018",
        "Name": "test-chapter-5-1",
        "Image": "strm/helloworld-http"
    }
}


###

# Delete a Worker Task
DELETE {{workerUrl}}/tasks/266592cd-960d-4091-981c-8c25c44b1018

###

# Get worker stats
GET {{workerUrl}}/stats

########## MANAGER API ##########

# Get Manager Tasks
GET {{managerUrl}}/tasks

### Create a Manager Task1

POST {{managerUrl}}/tasks

{
    "ID": "a7aa1d44-08f6-443e-9378-f5884311019e",
    "State": 2,
    "Task": {
        "State": 1,
        "ID": "bb1d59ef-9fc1-4e4b-a44d-db571eeed203",
        "Name": "test-chapter-10.1",
        "Image": "timboring/echo-server:latest",
        "ExposedPorts": {
            "7777/tcp": {}
        },
        "PortBindings": {
            "7777/tcp": "7777"
        },
        "HealthCheck": "/health"
    }
}

### Create a Manager Task2
POST {{managerUrl}}/tasks

{
    "ID": "6be4cb6b-61d1-40cb-bc7b-9cacefefa60c",
    "State": 2,
    "Task": {
        "State": 1,
        "ID": "21b23589-5d2d-4731-b5c9-a97e9832d021",
        "Name": "test-chapter-9.2",
        "Image": "timboring/echo-server:latest",
        "ExposedPorts": {
            "7777/tcp": {}
        },
        "PortBindings": {
            "7777/tcp": "7777"
        },
        "HealthCheck": "/healthfail"
    }
}

### Delete a Manager Task
DELETE {{managerUrl}}/tasks/21b23589-5d2d-4731-b5c9-a97e9832d021



### Health check -- chapter 9

### Getting
GET http://localhost:32768/health

### Health Fail
GET http://localhost:7777/healthfail

### Posting
POST http://localhost:7777
Content-Type: application/json

{
    "Msg": "hello world"
}
