@url=http://localhost:5555

# Get Worker Tasks
GET {{url}}/tasks

###

# Start a Worker Task
POST {{url}}/tasks

{
    "ID": "266592cd-960d-4091-981c-8c25c44b1018",
    "State": 2,
    "Task": {
        "State": 1,
        "ID": "266592cd-960d-4091-981c-8c25c44b1018",
        "Name": "test-chapter-5-1",
        "Image": "strm/helloworld-http"
    }
}


###

# Delete a Worker Task
DELETE {{url}}/tasks/266592cd-960d-4091-981c-8c25c44b1018
